name: olibox-core
base: core18
version: '0.1dev'
summary: Core functionality for Oli box
description: |
    Olibox_core module provides the basic functionality 
    to wrtie data from IR sensor and REST API to json files
    and publish this data to mqtt broker.
    This utility is particularly useful for Oli box.
grade: devel
confinement: strict

parts:
  olibox-core:
    source: https://github.com/m-yahya/snap-tutorial.git
    #source-tag: 0.1dev
    plugin: python
    #source: .
    requirements: ['requirements.txt']
  launcher:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av mylauncher.sh $SNAPCRAFT_PART_INSTALL/bin/

apps:
  olibox-core:
    command: mylauncher.sh olibox-core